import { Props } from "../screens/home/ListCard";

export const listCardArticleProps: Props = {
    title: 'Nega i Higijena',
    subTitle: '8 Rezultata',
    items: [
        {id:1, title:'Bebina koža – u čemu je razlika ?', type:'article', bodyHtml:`<b>Adipisicing</b> in nulla cillum ex amet minim anim ad sit ut duis. Non reprehenderit proident magna mollit do fugiat excepteur tempor in minim nulla incididunt reprehenderit magna. Eiusmod aliqua exercitation non irure tempor.`},
        {id:2, title:'Koliko često treba kupati bebu?', type:'article', bodyHtml:`<b>Fugiat</b> id nulla deserunt nisi velit ea ut tempor fugiat reprehenderit culpa non nisi. Incididunt laboris officia laboris et exercitation ex deserunt ullamco. Ex pariatur dolore nulla elit occaecat laborum dolore irure irure cupidatat ea non non qui. Aliquip ipsum veniam enim ut mollit non aliquip non. Amet adipisicing minim commodo ex fugiat sit id elit fugiat voluptate consectetur.`},
        {id:3, title:'Da li je bolje kupati bebu uveče ili ujutru?', type:'article', bodyHtml:`<b>Occaecat</b> sunt velit dolor dolor duis consequat officia eiusmod sint. Deserunt adipisicing exercitation eu minim mollit nulla adipisicing ad velit. Esse occaecat Lorem tempor id irure ullamco ad irure dolore duis velit quis fugiat commodo. Laboris laboris aliquip eu aliqua non minim aute veniam. Et consectetur deserunt exercitation aliquip consectetur veniam.`},
        {id:4, title:'Da li je prebrisavanje pelenom ili sunđerom dovoljno?', type:'article', bodyHtml:`<b>Velit</b> pariatur reprehenderit aliqua anim eu quis voluptate laboris ipsum. Aliqua pariatur elit irure cupidatat cillum incididunt ea minim nostrud non aliqua. Quis do officia labore ipsum laborum. Cillum laboris et proident commodo velit laboris labore et nulla culpa. Magna enim dolore duis fugiat. Do id aute ex sint aliquip dolor et.`},
        {id:5, title:'Postoji li idealna temperatura za kupanje?', type:'article', bodyHtml:`<b>Esse</b> culpa minim mollit laborum. Aute enim eiusmod laborum ex sunt laborum veniam dolor nisi est. Id incididunt fugiat magna sint ea amet. Ad fugiat cupidatat sunt enim enim excepteur deserunt pariatur ex pariatur minim deserunt nulla velit.`},
        {id:6, title:'Kada najranije možemo da kupamo bebu u ležećem položaju u kadici?', type:'article', bodyHtml:`<b>Quis</b> id eu nulla anim exercitation aute nisi. Duis aliquip qui enim reprehenderit do qui nulla ad consequat sint enim. Proident commodo occaecat voluptate proident ex cupidatat deserunt esse adipisicing qui. Minim do deserunt non enim consequat tempor aliquip labore qui amet sunt. Ea nisi proident incididunt velit.`},
        {id:7, title:'Koliko dugo beba sme da se kupa u kadi?', type:'article', bodyHtml:`<b>Enim</b> elit adipisicing amet irure cillum est laborum cupidatat officia ipsum minim nostrud amet fugiat. Nisi voluptate ex do veniam occaecat. Proident amet duis consequat eiusmod amet anim ex ullamco labore Lorem eiusmod.`},
        {id:8, title:'Da li tek rođene bebe treba kupati svake večeri?', type:'article', bodyHtml:`<b>Cupidatat</b> eu sint deserunt elit. Magna ex enim occaecat sit mollit officia ut dolor ipsum amet est qui reprehenderit consectetur. Est proident aliqua consequat consequat laboris.`},
    ],
};